name: data_encoder
description: Collection of decoders and parsers for string data from and to the Smart Contract
version: 1.0.0
repository: https://github.com/simonesestito/gethdomains

environment:
  sdk: ^3.2.1

# Add regular dependencies here.
dependencies:
  cid: ^1.0.1
  base32: ^2.1.3
  sha3: ^0.2.0
  bs58: ^1.0.2
  convert: ^3.1.1


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
