name: oracle
description: An oracle to verify domains which are registered on the GethDomain smart contract.
version: 1.0.0
publish_to: 'none'
repository: https://github.com/simonesestito/gethdomains

environment:
  sdk: ^3.2.1

# Add regular dependencies here.
dependencies:
  web3dart: ^2.7.2
  data_encoder:
    path: ../data_encoder
  socks5_io:
    git:
      url: https://github.com/simonesestito/dart_socks5_io.git
      ref: 736109deb205ebe6216efa1709eb40a4d423b369

dev_dependencies:
  lints: ^2.1.0
